baseURL: https://grupawolne.pl
languageCode: pl-pl
title: Grupa Wolne
theme: "PaperMod"

params:
  assets:
    disableHLJS: true
  footer: grupa wolne â¤ï¸ {year}
  displayFullLangName: true
  disableSpecial1stPost: true
  label:
    icon: /logo.svg

permalinks:
  events: :slug

defaultContentLanguage: pl
languages:
  pl:
    title: Grupa Wolne
    languageName: ğŸ‡µğŸ‡± polski
    weight: 1
    menu:
      main:
        - identifier: events
          name: Wydarzenia
          url: /
          weight: 1
        - identifier: about
          name: O nas
          url: /o-nas/
          weight: 2
        - identifier: contact
          name: Kontakt
          url: /kontakt/
          weight: 3
  en:
    title: Grupa Wolne
    languageName: ğŸ‡ºğŸ‡¸ english
    weight: 2
    menu:
      main:
        - identifier: events
          name: Events
          url: /
          weight: 1
        - identifier: about
          name: About
          url: /about/
          weight: 2
        - identifier: contact
          name: Contact
          url: /contact/
          weight: 3
  ua:
    title: Grupa Wolne
    languageName: ğŸ‡ºğŸ‡¦ ÑƒĞºÑ€Ğ°Ñ—Ğ½ÑÑŒĞºĞ¸Ğ¹
    weight: 3
    menu:
      main:
        - identifier: events
          name: ĞŸĞ¾Ğ´Ñ–Ñ—
          url: /
          weight: 1
        - identifier: about
          name: ĞŸÑ€Ğ¾ Ğ½Ğ°Ñ
          url: /pro-nas
          weight: 2
        - identifier: contact
          name: ĞšĞ¾Ğ½Ñ‚Ğ°ĞºÑ‚
          url: /kontakt
          weight: 3
  ru:
    title: Grupa Wolne
    languageName: ğŸ‡·ğŸ‡º Ñ€ÑƒÑÑĞºĞ¸Ğ¹
    weight: 4
    menu:
      main:
        - identifier: events
          name: Ğ¡Ğ¾Ğ±Ñ‹Ñ‚Ğ¸Ñ
          url: /
          weight: 1
        - identifier: about
          name: Ğ Ğ½Ğ°Ñ
          url: /o-nas
          weight: 2
        - identifier: contact
          name: ĞšĞ¾Ğ½Ñ‚Ğ°ĞºÑ‚
          url: /kontakt
          weight: 3